name: Deploy

on:
  push:
    branches: [ current ]

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Build API
        run: npm run build
        env:
          encryptionKey: ${{ secrets.ENCRYPTION_KEY }}
          jwtSecret: ${{ secrets.JWT_SECRET }}
          mongo: ${{ secrets.MONGO }}
          port: ${{ secrets.PORT }}
          rateLimit: ${{ secrets.RATE_LIMIT }}
          emailUser: ${{ secrets.EMAIL_USER }}
          emailPassword: ${{ secrets.EMAIL_PASSWORD }}

      - name: Deploy API
        run: npm run deploy
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
